---
development:
  dialect: "sqlite3"
  database: ./civitai_civitai_development.sqlite

test:
  dialect: "sqlite3"
  database: ./civitai_civitai_test.sqlite

production:
  dialect: "sqlite3"
  database: ./civitai_civitai_production.sqlite
