name = "civitai"
bin = "bin/civitai"
vcs = "git"
with_pop = true
with_sqlite = true
with_dep = false
with_webpack = false
with_nodejs = false
with_yarn = false
with_docker = false
with_grifts = true
as_web = true
as_api = false
